name: JellyLegs
author: TheDiamondYT
version: 1.1
main: JellyLegs\Main
api: [2.0.0, 3.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4]
commands:
    jellylegs:
        description: Enable or disable fall damage for you or others!
        permission: jellylegs.toggle.self
permissions:
    jellylegs.*:
        default: op
        description: Gives access to all JellyLegs permissions.
        children:
            jellylegs.toggle.self:
                default: op
                description: Allow use of the /jellylegs command on yourself.
            jellylegs.toggle.others:
                default: op
                description: Allow use of the /jellylegs command on others.
